pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'echo "Hellow World"'
                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
            }
        }
    }
}